name: Format Check

on:
  repository_dispatch:
    types: [format-check]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: Install dependencies
        run: npm ci

      - name: Run Biome Format & Lint
        run: npm run format && npm run fix

      - name: Check for changes
        id: git_diff
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.git_diff.outputs.changes == 'true'
        run: |
          git config --global user.name 'codey-bot[bot]'
          git config --global user.email 'codey-bot[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: format code with biome"
          git push origin HEAD:${{ github.event.client_payload.ref }}


